# Generated by Django 2.0.4 on 2018-04-18 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gudang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarisResep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gudang.Obat')),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaksi.Pelanggan')),
            ],
        ),
        migrations.AddField(
            model_name='barisresep',
            name='resep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaksi.Resep'),
        ),
    ]
